POST http://localhost:3333/videos
Content-Type: application/json


{
    "title": "Video node",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

GET http://localhost:3333/videos?search=node


###

PUT http://localhost:3333/videos/3e95ba54-1a20-4d19-915e-c0621fae50db
Content-Type: application/json


{
    "title": "Video 01",
    "description": "Esse é o primeiro video",
    "duration": 180
}

###

DELETE http://localhost:3333/videos/9cabd247-d4ba-46f6-92ea-868ec42b7eda